### ISSUE TITLE
Feature request: allow long-running/threaded evaluations (currently 'interrupted')

### ISSUE THREAD

**Issue by clojj** [atom-haskell/ide-haskell-repl#10]
Running a function which takes something longer than 2 seconds or so, instead of printing the evaluation result, the REPL just displays 'Interrupted'.

Tested using forkIO functions...maybe this only occurs in threaded executions (?)

Maybe some setting 'Allow long-running ...' or 'Wait maximum ms ...' could help, if it can not be detected automatically... ?

**Comment by lierdakil** [comment]
This would need some changes to architecture. I don't have much time right now, so if you want to try your hand at this, feel free.

Long story short, first there needs to be a way to manually kill long-running task. Second, we need to stream response messages, so that there is at least some indication of progress. This shouldn't be terribly complicated.

**Comment by clojj** [comment]
I can try take a look at it...
this is the 'source' of the issue, right ?

line 113 in ghci.coffee

```
@timeout = setTimeout (=>
  tkill @ghci.pid, 'SIGINT'
  @finished = true
  @timeout = null
  ), 1000
```

**Comment by lierdakil** [comment]
Yes. Basically, if a command is running for longer than 1 second, it's interrupted. I initially made this so that stupid commands like `[1..]` would terminate and not eat up all memory and hang the system. But I guess that manual interrupt option would work for this case well enough.

**Comment by lierdakil** [comment]
Done in 0.0.20
