### ISSUE TITLE
Tracing does not work on Windows

### ISSUE THREAD

**Issue by vasily-kirichenko** [atom-haskell/ide-haskell-repl#34]
In the normal REPL:

``` haskell
> trace "foo" 1
foo
1
```

In the haskell-ide-repl:

``` haskell
> trace "foo" 1
< 1
```

**Comment by lierdakil** [comment]
It does work. It just outputs traces to ide-haskell's 'repl' tab, or, if you don't have ide-haskell, to a div above repl input line (which is normally hidden). Reason being, `Debug.Trace.trace` writes traces to stderr -- that's where ghci's complaints end up as well. It's not easy (or frankly possible in general) to differentiate between the two.

**Comment by vasily-kirichenko** [comment]
I cannot find output anywhere:
![image](https://cloud.githubusercontent.com/assets/873919/19154335/c70d4710-8be2-11e6-9708-278e8f4d9a32.png)

**Comment by lierdakil** [comment]
Oh. You're on Windows, right... which probably means there's no stderr. Hold on, I will try to force stderr allocation. Not sure it'll work, but worth a try.

**Comment by lierdakil** [comment]
See if 0.1.9 helps with this. If not, then I'm out of ideas for the moment.

**Comment by vasily-kirichenko** [comment]
Thanks for your time, but it's not helped :( Everything is OK on linux, but no output on windows.

**Comment by lierdakil** [comment]
Okay, so after some investigation, my previous workaround seems to help some, but not exactly in the way I expected it to. So long story short, v0.1.10 should work (at least it did in a Win7 VM).

Apparently, GHC can't make up its mind if it wants to use platform-specific `0x0d``0x0a` as a newline separator or just `0x0a`, so that's why 0.1.9 wasn't working properly (although it did _eventually_ spit out trace output -- provided something actually put `0x0d``0x0a` on stderr -- f.ex. an error message).

**Comment by vasily-kirichenko** [comment]
It works with v0.1.10 on win 10. Thanks!
