### ISSUE TITLE
Some unicode problems

### ISSUE THREAD

**Issue by varosi** [atom-haskell/ide-haskell-repl#38]
![utfproblem](https://cloud.githubusercontent.com/assets/6051718/19704110/2289b192-9b0f-11e6-945c-8b266c6bd75e.png)

Latest version of everything on Windows 10

**Comment by lierdakil** [comment]
This is hopefully fixed in v0.4.4 

Not the most elegant fix -- it forces execution in a shell and runs `chcp` -- but it should work well enough, I hope:

![image](https://cloud.githubusercontent.com/assets/7275622/19711646/de4e2f04-9b3f-11e6-91f3-da039ef81678.png)

Might introduce some weirdness wrt `extraArgs` setting -- those might require additional escaping, but I'm not 100% sure about that.

**Comment by lierdakil** [comment]
It'd be nice if you could confirm that it works for you as well.

**Comment by varosi** [comment]
Cool! It works now just great!
Thanks a lot!
