### ISSUE TITLE
REPL is just empty

### ISSUE THREAD

**Issue by kurtextrem** [atom-haskell/ide-haskell-repl#67]
I am a total noob. But I followed all setup requirements in the docs. However, when I load up a file, like:
```haskell
foo :: Bool -> (Bool -> Bool)
foo True False = False
foo _ _ = True
```

and then click "Repl" in IDE-Haskell... simply nothing happens. I am totally confused. Isn't the Repl used to "Ctrl+S -> 'Open' using Ghci" and then show the Prelude/Main* thing?

![screenshot_36](https://user-images.githubusercontent.com/502146/38632803-16e0a2da-3dbe-11e8-95c3-7c4234944acf.png)

and I don't even understand this error:
![screenshot_37](https://user-images.githubusercontent.com/502146/38632819-211b446c-3dbe-11e8-88b5-18ef0790b54b.png)

**Comment by lierdakil** [comment]
The bottom panel is for debug/error messages. Haskell IDE → Open REPL menu item should open the REPL proper.

And the error is because of [Haskell Report 2010, Chapter 5](https://www.haskell.org/onlinereport/haskell2010/haskellch5.html):
> A Haskell program is a collection of modules, one of which, by convention, must be called `Main` and must export the value `main`. The value of the program is the value of the identifier `main` in module `Main`, which must be a computation of type `IO τ` for some type `τ` (see Chapter 7). When the program is executed, the computation `main` is performed, and its result (of type `τ`) is discarded.

Additionally, section 5.1 in the same chapter:
> An abbreviated form of module, consisting only of the module body, is permitted. If this is used, the header is assumed to be `module Main(main) where`.

So long story short, either name your module (not `Main`), via `module Foo where`, or define a function `main :: IO ()` (which can totally be `main = undefined`)

**Comment by kurtextrem** [comment]
I see, thank you for the explanation. That really helped and now it's working! Cheers for helping a noob that quickly :)
